CREATE TABLE ALUNO2 (RA NUMBER PRIMARY KEY, NOME VARCHAR2(50));

INSERT INTO ALUNO2 VALUES (1, 'VERGILIO SANTOS');
INSERT INTO ALUNO2 VALUES (2, 'DOLORES MENDES');
INSERT INTO ALUNO2 VALUES (3, 'JOSÉ SANTOS');
COMMIT;

SELECT * FROM ALUNO2;